name: dating_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.6
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  go_router: ^13.0.1
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-SemiBold.ttf
